Quiz/Quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

Quiz/main/urls.py
from django.urls import path
from main.views import *
from . import views
from django.contrib.auth.views import LoginView

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('',views.index, name = 'index'),
    path('register',views.register, name = 'register'),
     path('login/', LoginView.as_view(template_name='main/registration/login.html'), name='login'),
    #path('', RedirectView.as_view(url='kvizovi')),
    path('kategorije', KategorijeList.as_view(), name = 'kategorije'),
    path('kvizovi', KvizoviList.as_view(), name = 'kvizovi'),
    path('pitanja', PitanjaList.as_view(), name = 'pitanja'),
    path('opisi', OpisiList.as_view(), name = 'opisi'),
    
    path('create_kategorija/', views.createKategorija, name='create_kategorija'),
    path('create_kviz/', views.createKviz, name='create_kviz'),
    path('create_pitanje/', views.createPitanje, name='create_pitanje'),
    path('create_opis/', views.createOpis, name='create_opis'),

    path('update_kategorija/<str:pk>/', views.updateKategorija, name='update_kategorija'),
    path('update_kviz/<str:pk>/', views.updateKviz, name='update_kviz'),
    path('update_pitanje/<str:pk>/', views.updatePitanje, name='update_pitanje'),
    path('update_opis/<str:pk>/', views.updateOpis, name='update_opis'),

    path('delete_kategorija/<str:pk>/', views.deleteKategorija, name='delete_kategorija'),
    path('delete_kviz/<str:pk>/', views.deleteKviz, name='delete_kviz'),
    path('delete_pitanje/<str:pk>/', views.deletePitanje, name='delete_pitanje'),
    path('delete_opis/<str:pk>/', views.deleteOpis, name='delete_opis'),
]

Quiz/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'main\css\sb-admin-2.css' %}">
    <title>{% block title %}Library{% endblock %}</title>
</head>

<body>
    {% if user.is_authenticated %}
    <h1 class="nav justify-content-center">My library</h1>
    <div class="nav justify-content-center">
        <form action="{% url 'main:register' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="logout">Logout</button>
        </form>
    </div>
   

    <div id="sidebar">
        {% block sidebar %}
        <ul class="nav justify-content-center  navbar navbar-expand-lg navbar-dark">
            <li><a href="/" class="nav-link">Home</a></li>
            <li><a href="/kategorije" class="nav-link">Kategorije</a></li>
            <li><a href="/kvizovi" class="nav-link">Kvizovi</a></li>
            <li><a href="/pitanja" class="nav-link">Pitanja</a></li>
            <li><a href="/opisi" class="nav-link">Opis Pitanja</a></li>
        </ul>
        {% endblock %}
    </div>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    {% else %}
        <p>Niste prijavljeni.</p>
        
        <form action="{% url 'main:login' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Login</button>
          </form>
          <br>
        <form action="{% url 'main:register' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Register</button>
          </form>
          

    {% endif %}
    
</body>
</html>

Quiz/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>This is our homepage</h1>

    {% if user.is_authenticated %}
        <p>Vaše ime: {{ user.username }}</p>
    {% else %}
        <p>Niste prijavljeni.</p>
    {% endif %}
</body>
</html>