Quiz/Quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

Quiz/main/urls.py
from django.urls import path
from main.views import *
from . import views
from django.contrib.auth.views import LoginView

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('',views.index, name = 'index'),
    path('register',views.register, name = 'register'),
     path('login/', LoginView.as_view(template_name='main/registration/login.html'), name='login'),
    #path('', RedirectView.as_view(url='kvizovi')),
    path('kategorije', KategorijeList.as_view(), name = 'kategorije'),
    path('kvizovi', KvizoviList.as_view(), name = 'kvizovi'),
    path('pitanja', PitanjaList.as_view(), name = 'pitanja'),
    path('opisi', OpisiList.as_view(), name = 'opisi'),
    
    path('create_kategorija/', views.createKategorija, name='create_kategorija'),
    path('create_kviz/', views.createKviz, name='create_kviz'),
    path('create_pitanje/', views.createPitanje, name='create_pitanje'),
    path('create_opis/', views.createOpis, name='create_opis'),

    path('update_kategorija/<str:pk>/', views.updateKategorija, name='update_kategorija'),
    path('update_kviz/<str:pk>/', views.updateKviz, name='update_kviz'),
    path('update_pitanje/<str:pk>/', views.updatePitanje, name='update_pitanje'),
    path('update_opis/<str:pk>/', views.updateOpis, name='update_opis'),

    path('delete_kategorija/<str:pk>/', views.deleteKategorija, name='delete_kategorija'),
    path('delete_kviz/<str:pk>/', views.deleteKviz, name='delete_kviz'),
    path('delete_pitanje/<str:pk>/', views.deletePitanje, name='delete_pitanje'),
    path('delete_opis/<str:pk>/', views.deleteOpis, name='delete_opis'),
]

Quiz/main/models.py
from django.db import models

# Create your models here.

class Kategorija(models.Model):
    nazivKategorije = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.nazivKategorije


class Kviz(models.Model):
    naziv = models.CharField(max_length=100)
    opisKviza = models.CharField(max_length=255)
    kategorija = models.ManyToManyField(Kategorija)

    def __str__(self) -> str:
        return self.naziv


class Pitanje(models.Model):
    kviz = models.ForeignKey(Kviz, on_delete=models.CASCADE)
    naziv = models.CharField(max_length=50,blank=True,null=True)
    opis = models.OneToOneField('OpisPitanja', on_delete=models.CASCADE)
    odgovor1 = models.CharField(max_length=150)
    odgovor2 = models.CharField(max_length=150)
    odgovor3 = models.CharField(max_length=150)
    odgovor4 = models.CharField(max_length=150)
    tocan = models.IntegerField()
    savjet = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.naziv



class OpisPitanja(models.Model):
    tekst = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.tekst

Quiz/main/forms.py
from django.forms import ModelForm
from .models import *

class KategorijaForm(ModelForm):
    class Meta:
        model = Kategorija
        fields = '__all__'


class KvizForm(ModelForm):
    class Meta:
        model = Kviz
        fields = '__all__'

class PitanjeForm(ModelForm):
    class Meta:
        model = Pitanje
        fields = '__all__'

class OpisForm(ModelForm):
    class Meta:
        model = OpisPitanja
        fields = '__all__'
        

Quiz/main/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from main.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import *
from .filters import *


## Create your views here.

def index(request):
    return render(request,'base_generic.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')

    else:
        form = UserCreationForm()

    context = {'form': form}

    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('/')

    return render(request, 'main/registration/register.html', context)


class KategorijeList(ListView):
    model = Kategorija

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = KategorijaFilter(self.request.GET, queryset=self.get_queryset())
        return context


class KvizoviList(ListView):
    model = Kviz

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = KvizFilter(self.request.GET, queryset=self.get_queryset())
        return context


class PitanjaList(ListView):
    model = Pitanje

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PitanjaFilter(self.request.GET, queryset=self.get_queryset())
        return context

class OpisiList(ListView):
    model = OpisPitanja

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = OpisFilter(self.request.GET, queryset=self.get_queryset())
        return context

#Create
def createKategorija(request):

    form = KategorijaForm()
    if request.method == 'POST':
        print(request.POST)
        form = KategorijaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/kategorije')

    context = {'form': form}

    return render(request,'main/kategorija_form.html', context)


def createKviz(request):

    form = KvizForm()
    if request.method == 'POST':
        print(request.POST)
        form = KvizForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/kvizovi')

    context = {'form': form}

    return render(request,'main/kviz_form.html', context)


def createPitanje(request):

    form = PitanjeForm()
    if request.method == 'POST':
        print(request.POST)
        form = PitanjeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/pitanja')

    context = {'form': form}

    return render(request,'main/pitanje_form.html', context)

def createOpis(request):

    form = OpisForm()
    if request.method == 'POST':
        print(request.POST)
        form = OpisForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/opisi')

    context = {'form': form}

    return render(request,'main/opispitanja_form.html', context)

#Update
def updateKategorija(request, pk):

    kategorija = Kategorija.objects.get(id=pk)
    form = KategorijaForm(instance=kategorija)
    if request.method == 'POST':
        print(request.POST)
        form = KategorijaForm(request.POST, instance=kategorija)
        if form.is_valid():
            form.save()
            return redirect('/kategorije')

    context = {'form': form}

    return render(request,'main/kategorija_form.html', context)

def updateKviz(request, pk):

    kviz = Kviz.objects.get(id=pk)
    form = KvizForm(instance=kviz)
    if request.method == 'POST':
        print(request.POST)
        form = KvizForm(request.POST, instance=kviz)
        if form.is_valid():
            form.save()
            return redirect('/kvizovi')

    context = {'form': form}

    return render(request,'main/kviz_form.html', context)

def updatePitanje(request, pk):

    pitanje = Pitanje.objects.get(id=pk)
    form = PitanjeForm(instance=pitanje)
    if request.method == 'POST':
        print(request.POST)
        form = PitanjeForm(request.POST, instance=pitanje)
        if form.is_valid():
            form.save()
            return redirect('/pitanja')

    context = {'form': form}

    return render(request,'main/pitanje_form.html', context)

def updateOpis(request, pk):

    opis = OpisPitanja.objects.get(id=pk)
    form = OpisForm(instance=opis)
    if request.method == 'POST':
        print(request.POST)
        form = OpisForm(request.POST, instance=opis)
        if form.is_valid():
            form.save()
            return redirect('/opisi')

    context = {'form': form}

    return render(request,'main/opispitanja_form.html', context)

#Delete

def deleteKategorija(request, pk):
    kategorija = Kategorija.objects.get(id=pk)
    context = {'item':kategorija}

    if request.method == 'POST':
        kategorija.delete()
        return redirect('/kategorije')
    return render(request,'main/kategorija_delete.html', context)

def deleteKviz(request, pk):
    kviz = Kviz.objects.get(id=pk)
    context = {'item':kviz}

    if request.method == 'POST':
        kviz.delete()
        return redirect('/kvizovi')
    return render(request,'main/kviz_delete.html', context)

def deletePitanje(request, pk):
    pitanje = Pitanje.objects.get(id=pk)
    context = {'item':pitanje}

    if request.method == 'POST':
        pitanje.delete()
        return redirect('/pitanja')
    return render(request,'main/pitanje_delete.html', context)

def deleteOpis(request, pk):
    opis = OpisPitanja.objects.get(id=pk)
    context = {'item':opis}

    if request.method == 'POST':
        opis.delete()
        return redirect('/opisi')
    return render(request,'main/opispitanja_delete.html', context)

Quiz/templates/main/kategorija_delete.html
{% extends "base_generic.html" %}
{% block content %}

<p>Are you sure you want to delete "{{item}}"</p>

<form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'main:kategorije' %}" class="btn btn-danger">Cancel</a>
    <input type="submit" name="Confirm">
</form>

{% endblock %}

Quiz/templates/main/kategorija_form.html
{% extends "base_generic.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-primary" name="Submit">
</form>

{% endblock %}

Quiz/templates/main/kategorija_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block content %}
<div class="nav d-flex flex-column align-items-center">
    <h2>Kategorije</h2>
    <br>
    <a href="{% url 'main:create_kategorija' %}" class="btn btn-success ">Create Category</a>
    <br>
    <br>
</div>

<div class="nav d-flex flex-column align-items-center">
    <form method="get" >
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-info">Search</button>
    </form>
</div>

{% for kategorija in filter.qs %}
    <div class="kategorija">
        <p><strong>Kategorija:</strong> <span class="nazivKategorije">{{ kategorija.nazivKategorije }}</span></p>
        <a href="{% url 'main:update_kategorija' kategorija.id %}" class="btn btn-primary"> Update</a>
        <a href="{% url 'main:delete_kategorija' kategorija.id %}" class="btn btn-danger"> Delete</a>
    </div>
{% endfor %}
{% endblock %}

Quiz/templates/main/kviz_delete.html
{% extends "base_generic.html" %}
{% block content %}

<p>Are you sure you want to delete "{{item}}"</p>

<form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'main:kvizovi' %}">Cancel</a>
    <input type="submit" class="btn btn-danger" name="Confirm">
</form>

{% endblock %}

Quiz/templates/main/kviz_form.html
{% extends "base_generic.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-primary" name="Submit">
</form>

{% endblock %}

Quiz/templates/main/kviz_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block content %}

<div class="nav d-flex flex-column align-items-center">
    <br>
    <h2> Kvizovi </h2>
    <br>
    <a href="{% url 'main:create_kviz' %} " class="btn btn-success">Create Quiz</a>
    <br>
    <br>
</div>

<div class="nav d-flex flex-column align-items-center">
    <form method="get" >
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-info">Search</button>
    </form>
</div>
{% for kviz in filter.qs %}
    <div class="kviz">
        <p><strong>Naslov Kviza: </strong> <span class="naslov"> {{ kviz.naziv }}</span></p>
        <p><strong>Opis Kviza:</strong> <span class="opisKviza">{{ kviz.opisKviza }}</span></p>
        
            <p><strong>Kategorije Kviza: </strong> 
                {% for kategorija in kviz.kategorija.all %}
                    <span class="kategorijaKviza">{{kategorija}}</span>
                    {% endfor %}
                
            </p>
            <a href="{% url 'main:update_kviz' kviz.id %}" class="btn btn-primary"> Update</a>
            <a href="{% url 'main:delete_kviz' kviz.id %}" class="btn btn-danger"> Delete</a>
    </div>
{% endfor %}
{% endblock %}

Quiz/templates/main/opispitanja_delete.html
{% extends "base_generic.html" %}
{% block content %}

<p>Are you sure you want to delete "{{item}}"</p>

<form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'main:opisi' %}">Cancel</a>
    <input type="submit" class="btn btn-danger" name="Confirm">
</form>

{% endblock %}

Quiz/templates/main/opispitanja_form.html
{% extends "base_generic.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="btn btn-primary" name="Submit">
</form>

{% endblock %}

Quiz/templates/main/opispitanja_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block content %}
<div class="nav d-flex flex-column align-items-center">
    <br>
    <h2> Opisi Pitanja </h2>
    <br>
    <a href="{% url 'main:create_opis' %}" class="btn btn-success">Create Desc</a>
    <br>
    <br>
</div>

<div class="nav d-flex flex-column align-items-center">
    <form method="get" >
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-info">Search</button>
    </form>
</div>
{% for opis in filter.qs %}
    <div class="opis">
        <p><strong>Opis Pitanja: </strong> <span class="opisPitanja">{{ opis.tekst }}</span></p>
        <a href="{% url 'main:update_opis' opis.id %}" class="btn btn-primary"> Update</a>
        <a href="{% url 'main:delete_opis' opis.id %}" class="btn btn-danger"> Delete</a>
    </div>
{% endfor %}
{% endblock %}

Quiz/templates/main/pitanje_delete.html
{% extends "base_generic.html" %}
{% block content %}

<p>Are you sure you want to delete "{{item}}"</p>

<form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'main:pitanja' %}">Cancel</a>
    <input type="submit" class="btn btn-danger" name="Confirm">
</form>

{% endblock %}

Quiz/templates/main/pitanje_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="nav d-flex flex-column align-items-center">
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" class="btn btn-primary" name="Submit">
    </form>
</div>


{% endblock %}

Quiz/templates/main/pitanje_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block content %}
<div class="nav d-flex flex-column align-items-center">
    <br>
    <h2> Pitanja </h2>
    <br>
    <a href="{% url 'main:create_pitanje' %}" class="btn btn-success">Create Question</a>
    <br>
    <br>
</div>

<div class="nav d-flex flex-column align-items-center">
    <form method="get"  >
        {{ filter.form|bootstrap }}
        <button type="submit" class="btn btn-info">Search</button>
    </form>
</div>
{% for pitanje in filter.qs %}
    <div class="pitanje">
        <p><strong>Naziv Pitanja:</strong> <span class="naziv">{{ pitanje.naziv }}</span></p>
        <p><strong>Pripada Kvizu: </strong>  <span class="pripadaKvizu"> {{ pitanje.kviz }}</span><p>
        <p><strong>Opis Pitanja:</strong> {{ pitanje.opis }}</p>
        <h4>Odgovori</h4>
        <ol>
            <li>)   {{ pitanje.odgovor1 }}</li>
            <li>)   {{ pitanje.odgovor2 }}</li>
            <li>)   {{ pitanje.odgovor3 }}</li>
            <li>)   {{ pitanje.odgovor4 }}</li>
        </ol>
        <p><strong>Tocan odgovor: </strong>{{ pitanje.tocan }}</p>
        <p><strong>Hint: </strong>{{ pitanje.savjet }}</p>

        <a href="{% url 'main:update_pitanje' pitanje.id %}" class="btn btn-primary"> Update</a>
        <a href="{% url 'main:delete_pitanje' pitanje.id %}" class="btn btn-danger"> Delete</a>
    </div>
{% endfor %}
{% endblock %}